# Generated by Django 3.1.1 on 2020-09-26 19:26

from django.db import migrations, models
import gsheets.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
    ]
