# Generated by Django 3.1.1 on 2020-09-26 19:36

from django.db import migrations, models
import gsheets.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('test_field', models.CharField(max_length=127)),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
